# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '',
                'doc_host': 'https://camille1.github.io/rgb2gray/',
                'git_url': 'https://github.com/camille1/rgb2gray/',
                'lib_path': 'rgb2gray'},
  'syms': {'rgb2gray.converters': {'rgb2gray.converters.rgb2gray': ('converters.html#rgb2gray', 'rgb2gray/converters.py')}}}