# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_converter.ipynb.

# %% auto 0
__all__ = ['get_gs']

# %% ../00_converter.ipynb 4
from PIL import Image
import numpy as np
import cv2

# %% ../00_converter.ipynb 5
def get_gs(img: Image) -> np.array:
    img = img.convert("RGB")
    img_array = np.asarray(img)
    return cv2.cvtColor(np.asarray(img), cv2.COLOR_RGB2GRAY)
